Add option to fetch login
Dashlane/dashlane-cli pull request #216
Opened 2024-03-07 10:38 UTC by mzellho

This PR adds a little option to lookup the login for a credential, similar to the password-option.

2024-03-07 12:05 UTC, Mikescops commented
Hello,

Thanks for taking the time to open a PR here. I like the idea but I think `dcli login` is a little bit confusing as it may let think that's the way to login into the Dashlane account. 
Also, to avoid duplicating much code I think it would be better to use an option on `dcli password` instead. That way we can reuse most of the code and just make a condition when doing the copy in the pastebin. Something like `dcli password --login`.

Let me know what you think about this.

2024-03-07 12:20 UTC, mzellho commented
My pleasure, thanks so much for this awesome tool that saves me so much time every day.

Initially, I was going with "username", but then realised that what I wanted to fetch is the login. So if you are okay with "user" we could also use this?

Of course, sub-options of password would also be possible and produce less duplicate code.

Your call, really 🙂

2024-03-07 12:38 UTC, Mikescops commented
Alright, I'd go for the sub-option then, when I initially made the different commands I followed the content-types that we have in the vault : passwords, secure notes, secrets.

2024-03-07 13:54 UTC, mzellho commented
Alright, I added the sub-options discussed and also introduced to fetch the email. Any other bits of the credentials worth fetching via the cli?

2024-03-08 08:27 UTC, Mikescops commented on src/commands/index.ts
> +                '-c, --credential <type>',
Nitpick: Can you name this `field` please?

2024-03-08 08:28 UTC, Mikescops requested changes
Looks good to me, just a naming recommendation and we can go with this, thanks!

2024-03-08 08:33 UTC, mzellho commented
@Mikescops done, thank you!

2024-03-08 08:38 UTC, Mikescops approved these changes
Tested locally and it works well.

2024-03-08 08:39 UTC, merged